import { Stack, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FormProvider, TextField } from "src/Component/FormComponent";
import styles from "../styles/Home.module.css";

import { useForm } from "react-hook-form";

const Home: NextPage = () => {
  const methods = useForm({
    // resolver: yupResolver(LoginSchema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

  const {
    reset,
    setError,
    handleSubmit,
    formState: { errors, isSubmitting, submitCount },
  } = methods;

  const onSubmit = (data) => {
    console.warn("data", data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FormProvider methods={methods}>
          <Stack spacing={3}>
            <TextField name="email" label="Email" />
            <TextField name="password" label="Password" />
          </Stack>
        </FormProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
